### ISSUE TITLE
Please connect the snap to the `home` interface

### ISSUE THREAD

**Issue by brlin-tw** [chipaca/httpie-snap#2]
Some HTTPie features, like [sessions](https://httpie.org/doc#sessions) will be more handy if the file can be saved to the user's home directory.

With the same reason, `removable-media` interface should be asserted as well.

**Comment by BoboTiG** [comment]
Thanks for the clue @Lin-Buo-Ren, both interfaces will be added to the official snap package (coming shortly, it will be stored at https://github.com/httpie/httpie).

**Comment by chipaca** [comment]
For what it's worth, the current snap has those already :-)
I just forgot to close the issue.
I've not been paying attention to this github project, as I'd set it up to transfer the snap upstream but they weren't receptive to it back then.
Now they are, huzzah!
