### ISSUE TITLE
Changing ownership?

### ISSUE THREAD

**Issue by BoboTiG** [chipaca/httpie-snap#3]
Hello @chipaca ,

Thank you for having maintained the `http` snap package! :)
I am very sorry, I thought I already contacted you, I am sorry for the delay.

I am the maintainer of HTTPie and would like to improve overall packaging (including other Linux distributions, Windows and macOS packages) and so I am working on getting back all unofficial packages into one place. It would allow me to better control updates.

Maybe could we continue the discussion via email (mickael AT apible DOT io)?

Thanks a lot for your answer and work,

**Comment by chipaca** [comment]
Absolutely no problem.

**Comment by BoboTiG** [comment]
That's awesome, and again: thank you very much for your work!
